[project]
name = "torch-stuff"
version = "0.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.6.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
